/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTask: typeof import('./src/components/AddTask.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navi: typeof import('./src/components/Navi.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
  }
}
