/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskBtn: typeof import('./src/components/common/AddTaskBtn.vue')['default']
    Navi: typeof import('./src/components/templates/Navi.vue')['default']
    TaskForm: typeof import('./src/components/common/TaskForm.vue')['default']
    Tasks: typeof import('./src/components/templates/Tasks.vue')['default']
    TasksView: typeof import('./src/components/pages/TasksView.vue')['default']
  }
}
