/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskBtn: typeof import('./src/components/common/AddTaskBtn.vue')['default']
    DeleteBtn: typeof import('./src/components/common/DeleteBtn.vue')['default']
    DeleteForm: typeof import('./src/components/common/DeleteForm.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    SideBer: typeof import('./src/components/common/SideBer.vue')['default']
    TaskCard: typeof import('./src/components/templates/TaskCard.vue')['default']
    TaskForm: typeof import('./src/components/templates/TaskForm.vue')['default']
    Tasks: typeof import('./src/components/templates/Tasks.vue')['default']
    TasksView: typeof import('./src/components/pages/TasksView.vue')['default']
  }
}
