services:
  ta-webui:
    build:
      context: ta_front
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_API_BASE_URL: "${BACKEND_API_BASE_HOST}:${APP_GATEWAY_PORT}"
    image: ta-frontend:latest
    container_name: ta-webui
    ports:
      - 80:80
      - 443:443

  ta-gateway:
    build:
      context: ta_gateway
      dockerfile: Dockerfile
    image: ta-gateway:latest
    container_name: ta-gateway
    ports:
      - ${APP_GATEWAY_PORT}:${APP_GATEWAY_PORT}
    environment:
      APP_PORT: ${APP_GATEWAY_PORT}
      USER_AUTH_SERVICE_URL: "http://ta-user-auth:${USER_AUTH_PORT}"
      PROJECT_SERVICE_URL: "http://ta-project-service:${PROJECT_SERVICE_PORT}"
    depends_on:
      - ta-user-auth

  ta-user-auth:
    build:
      context: easy_auther/ea_backend
      dockerfile: Dockerfile
    image: ta-user-auth:latest
    container_name: ta-user-auth
    depends_on:
      - ta-postgres
    ports:
      - ${USER_AUTH_PORT}:${USER_AUTH_PORT}
    environment:
      APP_PORT: ${USER_AUTH_PORT}
      PGSQL_HOST: ta-postgres
      PGSQL_PORT: ${POSTGRES_PORT}
      PGSQL_USER: ${POSTGRES_USER}
      PGSQL_PASS: ${POSTGRES_PASSWORD}
      PGSQL_DB: ${POSTGRES_DB}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

  ta-project-service:
    build:
      context: ta_project_service
      dockerfile: Dockerfile
    image: ta-project-service:latest
    container_name: ta-project-service
    ports:
      - ${PROJECT_SERVICE_PORT}:${PROJECT_SERVICE_PORT}
    environment:
      APP_PORT: ${PROJECT_SERVICE_PORT}
      POSTGRES_HOST: ta-postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ta-postgres:
    image: postgres:17.2-alpine3.21
    container_name: ta-postgres
    ports:
      - ${POSTGRES_PORT}:5432
      #volumes:
      #  - ./postgresql/db_store:/var/lib/postgresql/data
      #  - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 5
