services:
  ta-webui:
    build:
      context: task_app_front
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_API_BASE_URL: "http://localhost:${BACKEND_PORT}"
    image: ta-frontend:latest
    container_name: ta-webui
    ports:
      - 80:80
      - 443:443

  ta-backend:
    build:
      context: task_app_back
      dockerfile: Dockerfile
    image: ta-backend:latest
    container_name: ta-backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      APP_PORT: ${BACKEND_PORT}
      POSTGRES_HOST: ta-postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ta-postgres:
    image: postgres:17.2-alpine3.21
    container_name: ta-postgres
    ports:
      - ${POSTGRES_PORT}:5432
      #volumes:
      #  - ./postgresql/db_store:/var/lib/postgresql/data
      #  - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 5
