apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-task-app-backend
  labels:
    name: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-task-app-backend
  template:
    metadata:
      labels:
        app: deploy-task-app-backend
    spec:
      containers:
        - name: task-app-backend
          image: task-app-backend:dev
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config-task-app-backend
---
apiVersion: v1
kind: Service
metadata:
  name: svc-task-app-backend
spec:
  type: NodePort
  selector:
    app: deploy-task-app-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: svc-task-app-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-task-app-backend
  labels:
    name: task-app
data:
  PGSQL_HOST: "svc-task-app-pgsql"
  PGSQL_PORT: "5432"
  PGSQL_USER: "pgsql"
  PGSQL_PASS: "password"
  PGSQL_DB: "pgsql"
